# Generated by Django 5.1.7 on 2025-03-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('appointment_datetime', models.DateTimeField()),
                ('staff_name', models.CharField(max_length=200)),
            ],
        ),
    ]
