# Generated by Django 5.1.7 on 2025-03-22 20:25

from django.db import migrations
from django.contrib.auth.models import User, Group, Permission
from django.db.models import Q

def create_admin_user(appps, schema_editor):
    user = User.objects.create_user(
        username='admin',
        password='admin123',
        first_name="Administrador",
        email="admin@admin.com"
    )

    group, created = Group.objects.get_or_create(name='admin')

    permissions = Permission.objects.all()
    group.permissions.set(permissions)

    user.groups.add(group)

    user.is_superuser = True
    user.is_staff = True
    user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('djangotemplateapp', '0002_appointment_creation_datetime'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
